### PR TITLE
fix swap and RC related to issue, fixes #104

### LINKED ISSUE #104: RC in Overlapper when compliment needs to be kept
One step at a time:

phix-remover only:
$ zcat I1.prOnly_R2.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 2:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
NTTAAAGTTTTTTTTTATATATACATATNTATNTATTATTTTATTATTATTTTTTATATATATATAAACATATTTGACTCGATTAAACCGAGACTTTAGAATAATCAGTAACAAATTAATATGTTCTCGACTTAAATAGAATGCATACAT
#AAFFF-FJFFJ-AFJJJJJJFFA<-JF#FJF#-<FF7J-<FFJJJFFFJJA<JJJJJJJJJJFJFFFFJFF<FJ<AJ7FAF-FJ-F--7F-----7A-AFFFFF-7-7AF7F<--7-7AJJ-F<-7---7<7<--7-77F-----7-7-

phix-remover and super-deduper:
$ zcat I1.prAndSd_R2.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 1:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
NTTAAAGTTTTTTTTTATATATACATATNTATNTATTATTTTATTATTATTTTTTATATATATATAAACATATTTGACTCGATTAAACCGAGACTTTAGAATAATCAGTAACAAATTAATATGTTCTCGACTTAAATAGAATGCATACAT
#AAFFF-FJFFJ-AFJJJJJJFFA<-JF#FJF#-<FF7J-<FFJJJFFFJJA<JJJJJJJJJJFJFFFFJFF<FJ<AJ7FAF-FJ-F--7F-----7A-AFFFFF-7-7AF7F<--7-7AJJ-F<-7---7<7<--7-77F-----7-7-
.. so it looks like it happens in the adapter-trimmer step, as you suspected. In case you're going to send this off for further testing, here's only that pair of reads:

$ zcat ../L5_I1_reads/L5_I1_R1_001.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 1:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
TTCAGGTTCAAATTCTCTTTATTTCAAGAACAACAACACTCCTCCGGATACATTGTTGGGTTTTGTGCCCTAAATAAAACCCATTTCGATATAATCAGATTTACTTATTAATAAAGATCAGAAATAA
+
FJJFJJAFJFJJ<JFFFJ<FJJJJJJJJJJJJJFJJJJJ--FJFJJAJAFFJF<-FAFJJJJ--7AJ-FFAJJJFJJJAFFFJ<FAJJJ7F-AJA<FFJJ-FFFFAF<FA-77FFA--AF--AFJJF

$ zcat ../L5_I1_reads/L5_I1_R2_001.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 2:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
NTTAAAGTTTTTTTTTATATATACATATNTATNTATTATTTTATTATTATTTTTTATATATATATAAACATATTTGACTCGATTAAACCGAGACTTTAGAATAATCAGTAACAAATTAATATGTTCTCGACTTAAATAGAATGCATACAT
+
#AAFFF-FJFFJ-AFJJJJJJFFA<-JF#FJF#-<FF7J-<FFJJJFFFJJA<JJJJJJJJJJFJFFFFJFF<FJ<AJ7FAF-FJ-F--7F-----7A-AFFFFF-7-7AF7F<--7-7AJJ-F<-7---7<7<--7-77F-----7-7-
You were also interested in whether overlapper does the same thing, so here's phix-remover, super-deduper, and overlapper:

(nothing in _SE)

$ zcat I1.olInstead_R1.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 1:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
NTTAAAGTTTTTTTTTATATATACATATNTATNTATTATTTTATTATTATTTTTTATATATATATAAACATATTTGACTCGATTAAACCGAGACTTTAGAATAATCAGTAACAAATTAATATGTTCTCGACTTAAATAGAATGCATACAT
+
#AAFFF-FJFFJ-AFJJJJJJFFA<-JF#FJF#-<FF7J-<FFJJJFFFJJA<JJJJJJJJJJFJFFFFJFF<FJ<AJ7FAF-FJ-F--7F-----7A-AFFFFF-7-7AF7F<--7-7AJJ-F<-7---7<7<--7-77F-----7-7-

$ zcat I1.olInstead_R2.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 1:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
TTCAGGTTCAAATTCTCTTTATTTCAAGAACAACAACACTCCTCCGGATACATTGTTGGGTTTTGTGCCCTAAATAAAACCCATTTCGATATAATCAGATTTACTTATTAATAAAGATCAGAAATAA
+
FJJFJJAFJFJJ<JFFFJ<FJJJJJJJJJJJJJFJJJJJ--FJFJJAJAFFJF<-FAFJJJJ--7AJ-FFAJJJFJJJAFFFJ<FAJJJ7F-AJA<FFJJ-FFFFAF<FA-77FFA--AF--AFJJF

.... um ..... they're swapped! R/F ....?!
So if raw is R1F and R2F
phix contaminat producest R1F R2f
phix then super-deduper produces R1F R2F
then phix -> sd -> Adapter trim produces R1F R2RC
so reads end up ---> ---> instead of ---> <---
and the 
phix -> sD -> overlapper produces
R2F R1F

From Matt's chat earlier.

### PR DESCRIPTION
**Pull request by msettles**
This fixes the swap and reverse complement issue #104 I also added in additional tests for when R1 is shorter than R2. Also the test for Engulf R1 was RC of what it should have been, so fixes broke that test, but looking at the test, the expected output was RC of what it should have been. All tests now pass, ready to pull.

### CODE REVIEW

File: AdapterTrimmer/src/adapter-trimmer.cpp [hunk 1]
```diff
@@ -90,15 +95,20 @@ int main(int argc, char** argv)
             if(vm.count("read1-input")) {
                 if (!vm.count("read2-input")) {
                     throw std::runtime_error("must specify both read1 and read2 input files.");
-                } else if (vm.count("read2-input") != vm.count("read1-input")) {
-                    throw std::runtime_error("must have same number of input files for read1 and read2");
                 }
                 auto read1_files = vm["read1-input"].as<std::vector<std::string> >();
                 auto read2_files = vm["read2-input"].as<std::vector<std::string> >();
+                std::cout << "read1:" << read1_files.size() << "\n";
+                std::cout << "read2:" << read2_files.size() << "\n";
```
Comment (dstreett) [inline AdapterTrimmer/src/adapter-trimmer.cpp]: This can mess stuff up - remove any stdout. if you want to tell users stuff either put it in stats or throw runtime error.

File: Overlapper/test/testoverlapper.cpp [hunk 2]
```diff
@@ -114,15 +144,73 @@ TEST_F(Overlapper, perfectOverlap) {
...
+    InputReader<PairedEndRead, PairedEndReadFastqImpl> ifp(in1, in2);
+    spReadBase rb;
+    
+    OverlappingCounters counters;   
+
+    while(ifp.has_next()) {
+        auto i = ifp.next();
+        PairedEndRead *per = dynamic_cast<PairedEndRead*>(i.get());
+        rb = check_read(*per, misDensity, 10, 10, kmer, kmerOffset);
+        ASSERT_EQ(rb, nullptr);
```
Comment (dstreett) [inline Overlapper/test/testoverlapper.cpp]: Nioce!

File: Stats/src/stats.cpp [hunk 3]
```diff
@@ -75,18 +80,21 @@ int main(int argc, char** argv)
...
+                    throw std::runtime_error("must have same number of input files for read1 and read2");
+                }
 
                 for(size_t i = 0; i < read1_files.size(); ++i) {
                     bi::stream<bi::file_descriptor_source> is1{check_open_r(read1_files[i]), bi::close_handle};
                     bi::stream<bi::file_descriptor_source> is2{check_open_r(read2_files[i]), bi::close_handle};
                    
                     InputReader<PairedEndRead, PairedEndReadFastqImpl> ifp(is1, is2);
-                    helper_stats(ifp, pe, se, counters );
+                    // std::cout << "read file: " << read1_files[i] << ":" << ifp.has_next() << "\n";
```
Comment (dstreett) [inline Stats/src/stats.cpp]: Just get ride of this. It was used for debugging and won't be helpful down the road.

File: AdapterTrimmer/src/adapter-trimmer.cpp (hunk 1 above)
Comment (msettles) [reply AdapterTrimmer/src/adapter-trimmer.cpp]: I had these in there while debugging the issue with multiple input file (ex -1 file1.fastq file2.fastq) issue.  removing

File: Stats/src/stats.cpp (hunk 3 above)
Comment (msettles) [reply Stats/src/stats.cpp]: Sure, but this is still an issue as the app currently (it says it does) does not support multiple input files.  ifp.has_next() returns False after the first file finished preventing the second file from processing. I tried to figure it out but was unable to. Will make sure its a proper issue, if not already

**Comment by msettles** [comment]
Ok, this should be the final mod for the pull request

cut_trim expected behavior:
cut_trim is expected to be one of the first apps used in a preprocessing pipeline
such as when you want to statically trim off X bases from the end of a read (cut_right), due to 
quality, and/or to trim off primer sequence from the beginning of a read (cut_left). As such both
cut_left and cut_right should act on the original length of the read.

max_length then prevents the final cut length from being greater than max_length applying an
additional cut to end of the read if applicable. If one wished to simulate smaller sized reads
can run cut_trim with max_length (no cut to left or right) to effectively reduce the size of reads.

**Comment by msettles** [comment]
Not sure where we are at on this? @dstreett did you do the final review? ok to merge?

**Comment by joe-angell** [comment]
lgtm, but there are conflicts now, :)

**Comment by msettles** [comment]
Pull request is ready for final review, merged in Joe's mods, no conflicts, passes make test and my 5M read test dataset.

**Comment by joe-angell** [comment]
lgtm
